name: "Build is Healthy"

on:
  push:
    branches: [ master ]
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:

  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Installing Node
        uses: actions/setup-node@v4
        with:
          # use node version Heroku buildpack uses
          node-version: '18.20.4'
      - name: Install dependencies
        run: npm install --workspaces
      - name: Build backend
        run: npm run build --prefix backend
      - name: Run backend tests
        run: npm run test --prefix backend

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Installing Node
        uses: actions/setup-node@v4
        with:
          # use node version Heroku buildpack uses
          node-version: '18.20.4'
      - name: Install dependencies
        run: npm install --workspaces
      - name: Build frontend
        run: npm run build --prefix frontend
      - name: Run frontend tests
        run: echo "TODO, add frontend tests"